# Generated by Django 3.1.2 on 2020-11-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Juego'),
        ),
    ]
